`timescale 1ns/1ps

module fifo
    #(
        parameter DATA_WIDTH = 8,
                  ADDR_WIDTH = 3
    ) (
        input  logic clk,
        input  logic reset,
        input  logic rd,
        input  logic wr,
        input  logic [DATA_WIDTH-1:0] w_data,
        output logic [DATA_WIDTH-1:0] r_data,
        output logic [ADDR_WIDTH:0] count,
        output logic empty,
        output logic full
    );

    // Addresses generated by controller
    logic [ADDR_WIDTH-1:0] w_addr;
    logic [ADDR_WIDTH-1:0] r_addr;

    // Memory write enable
    logic wr_en;
    logic rd_en; 

    // Controller
    fifo_controller_w1r1 #(
        .ADDR_WIDTH(ADDR_WIDTH)
    ) controller (
        .clk(clk),
        .reset(reset),
        .rd(rd),
        .wr(wr),
        .empty(empty),
        .full(full),
        .count(count), 
        .w_addr(w_addr),
        .r_addr(r_addr)
    );

    // Only write when wr is asserted AND FIFO isn't full
    assign wr_en = wr && !full;
    assign rd_en = rd && !empty; 
    
    // Memory
    reg_file_w1r1 #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) memory (
        .clk(clk),
        .wr_en(wr_en),
        .rd_en(rd_en),
        .w_addr(w_addr),
        .r_addr(r_addr),
        .w_data(w_data),
        .r_data(r_data)
    );

endmodule